export const COMMON_TIMEZONES: { value: string; label: string }[] = [
    { value: "UTC", label: "UTC" },
    { value: "Pacific/Honolulu", label: "Honolulu (UTC−10)" },
    { value: "America/Anchorage", label: "Anchorage (UTC−9)" },
    { value: "America/Los_Angeles", label: "Los Angeles (UTC−8)" },
    { value: "America/Phoenix", label: "Phoenix (UTC−7)" },
    { value: "America/Denver", label: "Denver (UTC−7)" },
    { value: "America/Chicago", label: "Chicago (UTC−6)" },
    { value: "America/Mexico_City", label: "Mexico City (UTC−6)" },
    { value: "America/New_York", label: "New York (UTC−5)" },
    { value: "America/Toronto", label: "Toronto (UTC−5)" },
    { value: "America/Halifax", label: "Halifax (UTC−4)" },
    { value: "America/Sao_Paulo", label: "São Paulo (UTC−3)" },
    { value: "America/Buenos_Aires", label: "Buenos Aires (UTC−3)" },
    { value: "Atlantic/Azores", label: "Azores (UTC−1)" },
    { value: "Europe/London", label: "London (UTC+0)" },
    { value: "Europe/Dublin", label: "Dublin (UTC+0)" },
    { value: "Europe/Lisbon", label: "Lisbon (UTC+0)" },
    { value: "Europe/Paris", label: "Paris (UTC+1)" },
    { value: "Europe/Berlin", label: "Berlin (UTC+1)" },
    { value: "Europe/Madrid", label: "Madrid (UTC+1)" },
    { value: "Europe/Amsterdam", label: "Amsterdam (UTC+1)" },
    { value: "Europe/Rome", label: "Rome (UTC+1)" },
    { value: "Africa/Lagos", label: "Lagos (UTC+1)" },
    { value: "Europe/Athens", label: "Athens (UTC+2)" },
    { value: "Europe/Helsinki", label: "Helsinki (UTC+2)" },
    { value: "Africa/Cairo", label: "Cairo (UTC+2)" },
    { value: "Africa/Johannesburg", label: "Johannesburg (UTC+2)" },
    { value: "Europe/Istanbul", label: "Istanbul (UTC+3)" },
    { value: "Europe/Moscow", label: "Moscow (UTC+3)" },
    { value: "Asia/Riyadh", label: "Riyadh (UTC+3)" },
    { value: "Asia/Dubai", label: "Dubai (UTC+4)" },
    { value: "Asia/Tehran", label: "Tehran (UTC+3:30)" },
    { value: "Asia/Karachi", label: "Karachi (UTC+5)" },
    { value: "Asia/Kolkata", label: "Kolkata (UTC+5:30)" },
    { value: "Asia/Kathmandu", label: "Kathmandu (UTC+5:45)" },
    { value: "Asia/Dhaka", label: "Dhaka (UTC+6)" },
    { value: "Asia/Bangkok", label: "Bangkok (UTC+7)" },
    { value: "Asia/Jakarta", label: "Jakarta (UTC+7)" },
    { value: "Asia/Hong_Kong", label: "Hong Kong (UTC+8)" },
    { value: "Asia/Shanghai", label: "Shanghai (UTC+8)" },
    { value: "Asia/Singapore", label: "Singapore (UTC+8)" },
    { value: "Asia/Taipei", label: "Taipei (UTC+8)" },
    { value: "Australia/Perth", label: "Perth (UTC+8)" },
    { value: "Asia/Tokyo", label: "Tokyo (UTC+9)" },
    { value: "Asia/Seoul", label: "Seoul (UTC+9)" },
    { value: "Australia/Adelaide", label: "Adelaide (UTC+9:30)" },
    { value: "Australia/Sydney", label: "Sydney (UTC+10)" },
    { value: "Australia/Brisbane", label: "Brisbane (UTC+10)" },
    { value: "Pacific/Guam", label: "Guam (UTC+10)" },
    { value: "Pacific/Noumea", label: "Nouméa (UTC+11)" },
    { value: "Pacific/Auckland", label: "Auckland (UTC+12)" },
    { value: "Pacific/Fiji", label: "Fiji (UTC+12)" },
    { value: "Pacific/Chatham", label: "Chatham (UTC+12:45)" },
];
