services:
    web:
        image: ${DOCKERHUB_USERNAME}/woohoo-web:latest
        ports: !reset []
        networks:
            - woohoo_network
            - caddy_net

    migrate:
        image: ${DOCKERHUB_USERNAME}/woohoo-web:latest

    cron:
        image: ${DOCKERHUB_USERNAME}/woohoo-cron:latest

networks:
    caddy_net:
        external: true
